# azure-to-oci-daily-extract.yaml
trigger: none
pool: "msalowgts-devopvmss"
pr: none
schedules:
- cron: "0 12 * * *"
  displayName: Daily at 7am (UTC)
  branches:
    include:
    - master
  always: true

parameters:
- name: logFrequency
  type: string
  default: '100'

# Azure
- name: azureStorageAccount
  type: string
  default: 'mystorageacct'
- name: azureBlobPrefix
  type: string
  default: ''
- name: azureSasToken
  type: string
  default: $(AZURE_CONTAINER_SAS)

# OCI
- name: ociRegion
  type: string
  default: 'us-ashburn-1'
- name: ociNamespace
  type: string
  default: 'idr67sb5tyab'
- name: ociOutBucket
  type: string
  default: 'revpred-archive-uat'

# Working dirs
- name: downloadDirectory
  type: string
  default: 'download/'
- name: uploadDirectory
  type: string
  default: 'upload/'

# OCI Secure Files
- name: ociCliDestConfigEnv
  type: string
  default: $(ociApiConfigDest.secureFilePath)
- name: ociApiKeyDestEnv
  type: string
  default: $(ociApiKeyDest.secureFilePath)

variables:
  OCI_CLI_HOME: '/home/AzDevOps/.oci'
  OCI_CLI_BIN: '/home/AzDevOps/bin'

stages:
- stage: azure_to_oci
  jobs:
  - job: run_transfer
    timeoutInMinutes: 600
    steps:
    - task: DownloadSecureFile@1
      name: ociApiConfigDest
      inputs:
        secureFile: 'devops_oci_DEST_api_config_file.txt'

    - task: DownloadSecureFile@1
      name: ociApiKeyDest
      inputs:
        secureFile: 'devops_oci_DEST_api_key.pem'

    - task: Bash@3
      displayName: Install Azure & OCI CLI
      inputs:
        targetType: inline
        script: |
          if ! command -v az >/dev/null 2>&1; then
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi
          if [ ! -f "$OCI_CLI_BIN/oci" ]; then
            bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
          fi
          mkdir -p $OCI_CLI_HOME
          cp -f ${{ parameters.ociCliDestConfigEnv }} $OCI_CLI_HOME/config
          cp -f $(ociApiKeyDest.secureFilePath) $OCI_CLI_HOME/oci_api_key.pem
          $OCI_CLI_BIN/oci setup repair-file-permissions --file $OCI_CLI_HOME/config
          $OCI_CLI_BIN/oci setup repair-file-permissions --file $OCI_CLI_HOME/oci_api_key.pem
          echo "##vso[task.prependpath]$OCI_CLI_BIN"

    - task: PowerShell@2
      displayName: Run Transfer Script
      inputs:
        targetType: filePath
        filePath: transfer.ps1
        arguments: >
          -azureStorageAccount "${{ parameters.azureStorageAccount }}"
          -azureBlobPrefix "${{ parameters.azureBlobPrefix }}"
          -azureSasToken "${{ parameters.azureSasToken }}"
          -ociRegion "${{ parameters.ociRegion }}"
          -ociNamespace "${{ parameters.ociNamespace }}"
          -ociOutBucket "${{ parameters.ociOutBucket }}"
          -downloadDirectory "${{ parameters.downloadDirectory }}"
          -uploadDirectory "${{ parameters.uploadDirectory }}"
          -logFrequency "${{ parameters.logFrequency }}"
