#azure-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-training-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 512Mi