# cleanup-images-azure-pipelines.yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: "vmss Linux RTI network"

steps:
  - task: Bash@3
    displayName: Clean Up old Images and containers
    inputs:
      targetType: 'inline'
      script: |
        docker system prune -af