# daily-extract-azure-pipeline.yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool: "msalowgts-devopvmss"
pr: none
schedules:
- cron: "0 12 * * *"
  displayName: Daily at 7am (UTC)
  branches:
    include:
    - master
  always: true
variables:
- group: 'Azure Variables'
stages:
- stage: prod
  jobs:
  - job: run_extract
    steps:
    - task: AzureCLI@2
      name: "Run_Extract"
      inputs:
        azureSubscription: 'cfo-apps-revpred-deploy-prod-AKSLOWPRODPRV002'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |

          Install-Module -Name Az.Storage -AllowClobber -Scope CurrentUser -Force
          
          $contextFrom = New-AzStorageContext -StorageAccountName '$(AzureStorageAccountProd)' -SasToken '$(AzureSASTokenProd)'
          $contextTo =  New-AzStorageContext -StorageAccountName '$(AzureStorageAccountExtract)' -SasToken '$(AzureSASTokenExtract)'

          $blobContainers=@()
          Get-AzStorageContainer -context $contextFrom -verbose
          $original=Get-AzStorageContainer -context $contextFrom 
          $original |  % { $blobContainers += Get-AzStorageBlob -Container $_.Name -Context $contextFrom }

          [DateTime] $LastModifiedSince = [DateTime]::Now.AddDays(-1)

          $modifiedBlobs = $blobContainers | ?{ ($_.LastModified -gt  "$LastModifiedSince")}
          $modifiedContainers = $blobContainers | select -expand BlobClient  | select -expand BlobContainerName -unique
          write-host "modified containers"
          $modifiedContainers | Out-String | Write-host
          write-host "modified blobs"
          $modifiedBlobs | Out-String | Write-host
          
          # create containers needed for the blob copy
          $modifiedContainers | % { 
            If (-not (Get-AzStorageContainer -name $_ -Context $contextTo )) { 
              write-host New-AzStorageContainer -Name "$_"  -Context $contextTo.StorageAccountName 
              if (-not $dryrun) {
                New-AzStorageContainer -Name "$_"  -Context $contextTo 
                }
              }
            }

          $modifiedBlobs | % {
              # copy the blob
              Write-host Start-AzStorageBlobCopy `
                  -SrcContainer $_.BlobClient.BlobContainerName `
                  -SrcBlob $_.Name `
                  -DestContainer $_.BlobClient.BlobContainerName `
                  -DestBlob $_.Name  `
                  -Context $contextFrom.StorageAccountName `
                  -DestContext $contextTo.StorageAccountName `
                  -Force
              if (-not $dryrun) {
                  Start-AzStorageBlobCopy `
                    -SrcContainer $_.BlobClient.BlobContainerName `
                    -SrcBlob $_.Name `
                    -DestContainer $_.BlobClient.BlobContainerName `
                    -DestBlob $_.Name  `
                    -Context $contextFrom `
                    -DestContext $contextTo `
                    -Force
                    }
                  }
          # clean any files greater than the specified number of days old from extract
          $daysToKeep = "$(daysToKeep)"
          if ($daysToKeep -ne "") {
            $blobs=@()
            Get-AzStorageContainer -context $contextTo | % { 
                    $blobs += Get-AzStorageBlob -Container $_.Name -Context $contextTo
                    }
            write-host "found files on $contextTo.StorageAccountName"
            $blobs | select -expand BlobClient | Out-String | Write-host
            $old = $blobs | ?{ ($_.LastModified -lt  $([DateTime]::Now.AddDays(-$daysToKeep))) } 
            write-host "Removing files more than $(daysToKeep) days old"
            $old | select -expand BlobClient | Out-String | Write-host
            if (-not $dryrun) {
              $old | Remove-AzStorageBlob -context $contextTo
              }
            }

